In [20]:
# PREAMBLE - YOU NEED TO EXECUTE THIS CELL USING [SHIFT+RETURN]
# BUT YOU DO NOT NEED TO READ OR UNDERSTAND ANYTHING WITHIN IT
# THE COURSEWORK BEGINS IN THE CELL BELOW

import datetime
import numpy as np

def verify(w, x, y):
    cnFlag = False; tdFlag = False; dtFlag = False;
    dy = y[0:2]; mn = y[3:5]; yr = y[6:10]
    dto = str(datetime.datetime.now())
    if len(x) == 8:
        cnFlag = True
    else:
        st = 'Your candidate number is not entered correctly'
    if len(y) == 10:
        tdFlag = True
    else:
        st = 'You have not entered today' + chr(39) + 's date in the correct format'
    if dto[0:4] == yr and dto[5:7] == mn and dto[8:10] == dy:
        dtFlag = True
    else:
        st = 'You have not entered today' + chr(39) + 's date correctly'

    if cnFlag == True and tdFlag == True and dtFlag == True:
        st = ('The coursework is proceeding using\nName: ' + candidateName +
             '\nCandidate Number: ' + candidateNo +
             '\nToday' + chr(39) + 's date: ' + today[0:2] + '/' + today[3:5] + '/' + today[6:10])
    else:
        st = 'Go back to Candidate Information to correct input data.'
    print(st)

def f(z, q):
    # [a, d, b, c]
    # z = [int(p) for p in [dy, dto[2:4], mn, dto[0:2]]]
    # q = 0.02127659574/43
    cfs = np.zeros((6,1)); A = np.zeros((2, 2)); I = np.zeros((2,2))
    cfs[0] = np.sqrt(z[0]**2 - 2*z[0]*z[1] + z[1]**2 + 4*z[2]*z[3])
    cfs[1] = 0.5*(z[0] + z[1] - cfs[0])
    if cfs[1] > 0:
        cfs[1] = cfs[1]**q
    else:
        cfs[1] = -(-cfs[1])**q 
    cfs[2] = (0.5*(z[0] + z[1] + cfs[0]))**q; cfs[3] = z[0] - z[1]; 
    cfs[4] = -cfs[0] + cfs[3]; cfs[5] = cfs[3] + cfs[0]
    A[0,0] = -(cfs[4]*cfs[1] - cfs[5]*cfs[2])/(2*cfs[0]); A[0,1] = z[2]*(cfs[2] - cfs[1])/cfs[0]
    A[1,0] = -cfs[4]*cfs[5]*(cfs[2] - cfs[1])/(4*z[2]*cfs[0]); A[1,1] = (cfs[5]*cfs[1] - cfs[4]*cfs[2])/(2*cfs[0])
    I[0,0] = 1; I[1, 1] = 1
    return A

# Coursework 1 - Basics of Python

## Candidate Information

Run the cell below using [Shift + Return] and enter your information at the prompts.  Ensure that your candidate number has 8 digits and that you enter the year in the required format, putting a '/' between the day, month and year.

In [22]:
candidateName = input('Name: ')
candidateNo = input('Candidate Number: ')
today = input('Enter today' + chr(39) + 's date [dd/mm/yyyy]: ')

Name: Matthew Scase
Candidate Number: 20122012
Enter today's date [dd/mm/yyyy]: 03/09/2021


Run the cell below using [Shift + Return] to check your inputs are valid.  If you have entered your information correctly you will see your name, candidate number and today's date output.  If you have entered your information incorrectly you need to go back and re-run the cell above.

In [23]:
verify(candidateName, candidateNo, today)

The coursework is proceeding using
Name: Matthew Scase
Candidate Number: 20122012
Today's date: 03/09/2021


## Section A

1) Determine whether your candidate number that is stored in the variable `candidateNo` is an integer, a floating point decimal or a text string by using the `type` command. $\tag{1 Mark}$

In [ ]:
type

2) Convert your candidate number to an integer and evaluate your candidate number squared.  Print out your answer to the screen using `print`. $\tag{1 Mark}$

In [ ]:
print()

## Section B

Two matrices $\textbf{M}_1$ and $\textbf{M}_2$ that are stored as `np.array`s can be multiplied together using `np.matmul`.  

For example we can represent the matrices
$$\textbf{M}_1 = \left(\begin{array}{rr} 1 & -2 \\ 0 & 1\end{array}\right),
\qquad
\textbf{M}_2 = \left(\begin{array}{rr} 3 & 1 \\ -1 & 2\end{array}\right)$$
in Python as

    M1 = np.array([[1, -2], [0, 1]])
    M2 = np.array([[3, 1], [-1, 2]])
    
We can calculate their product using

    np.matmul(M1, M2)
    
which gives us the answer
$$\textbf{M}_1\times\textbf{M}_2 = \left(\begin{array}{rr} 5 & -3 \\ -1 & 2\end{array}\right)$$

In [24]:
M1 = np.array([[1, -2], [0, 1]])
M2 = np.array([[3, 1], [-1, 2]])
np.matmul(M1, M2)

array([[ 5, -3],
       [-1,  2]])

Run the cell below using [Shift + Return] to generate the arrays that you will be working with in this coursework.

In [25]:
I = np.identity(2); print('I =\n', I)
A = f([int(p) for p in [dy, dto[2:4], mn, dto[0:2]]], 0.02127659574/43); print('A =\n', A)

I =
 [[1. 0.]
 [0. 1.]]
A =
 [[-0.55726889  0.55774281]
 [ 1.23942846  0.55821672]]


You can output the entries of an array rounded to the nearest integer using `print(np.round(array_name).astype(int))`.  So for example we can see the array `A` with all its entries rounded to the nearest integer by running the cell below.

In [26]:
print(np.round(A).astype(int))

[[-1  1]
 [ 1  1]]


1) Using `np.matmul` and a `for` loop, evaluate $\textbf{A}^{2021}$ and output the answer to the notebook using `print`. 

[**Hint**: Start by defining an array `B` to be equal to the identity array `I`.  Then set up a `for` loop that updates the elements of `B` by multiplying the array on the left by `A`.]

In [27]:
B = I
for i in range(2021):
    B = np.matmul(A, B)
print(B)

[[ 3.          8.99999999]
 [19.99999999 20.99999998]]


2) What do you notice about your solution when you round each entry to the nearest integer?

In [28]:
print(np.round(B).astype(int))

[[ 3  9]
 [20 21]]
