<a id="index"></a>

# Python Glossary

**Mathematical Methods for Chemical Engineers (MTHS1008)**

**Dr Matthew Scase**

Listed below are expressions, terms and commands you should be familiar with by the end of the Year 1 Autumn Semester Python course.

| Functions | Mathematical Operators   | Conditional Statements| Control Statements | Special Functions      | Matrix Functions |
|:--------- |:----------------------   |:--------------------- |:------------------ |:---------------------- |:---------------- |
| [as](#import)     | [+](#operators)  | [==](#isequal)        | [else](#else)      | [numpy.abs()](#abs)    | [numpy.array()](#array) |
| [float()](#float) | [-](#operators)  | [!=](#isnotequal)     | [for](#for)        | [numpy.arccos()](#abs) | [numpy.zeros()](#zeros) |
| [format()](#format) | [*](#operators)  | [>](#inequality)    | [if](#if)          | [numpy.arcsin()](#abs)| [numpy.matmul()](#matmul) |
| [import](#import) | [/](#operators)  | [<](#inequality)     | [in](#for)         | [numpy.arctan()](#abs) |  |
| [input()](#input) | [**](#operators) | [>=](#inequality)     | [is](#is)          | [numpy.cos()](#abs)   |  |
| [int()](#int)     |                  | [<=](#inequality)     | [while](#while)    | [numpy.exp()](#abs)   |  |
| [print()](#print) |                  |                       |                    | [numpy.log()](#abs)   |  |
| [range()](#range) |                  |                       |                    | [numpy.sqrt()](#abs)  |  |
| [str()](#str)     |                  |                       |                    | [numpy.sin()](#abs)   |  |
| [sum()](#sum)     |                  |                       |                    | [numpy.tan()](#abs)   |  |
| [type()](#type)   |                  |                       |                    |                       |  |

### FUNCTIONS

<a id = 'print'></a>

        print()
The `print()` function prints the `argument` (the bit that goes into the brackets after the word `print`) to the screen.  Text contained between single quotes is printed directly to the screen.  Evaluations that do not appear in single quotes are calculated and the output written to the screen (such as the sum `2 + 4` in the example below).

In [1]:
print('This text will be printed to the screen:', 2 + 4)

This text will be printed to the screen: 6


[Back](#index)

<a id = 'input'></a>

        input()
The `input()` function writes the string argument it is given to the screen and waits for user input.  Whatever the user inputs will be stored as a `string`.  In the example given below the user input is stored as a string in a variable named `A`.

In [2]:
A = input('This text will be printed to the screen: ')
print(A)

This text will be printed to the screen: rhubarb
rhubarb


[Back](#index)

<a id = 'type'></a>

        type()
The `type()` function is equal to `int` if the argument is an integer, such as in the example above, or `float` if the argument is a decimal (try the example below but setting `B = 5.0`), or `str` if the argument is a string/text (try the example below but setting `B = '5'`).

In [3]:
B = 5
type(B)

int

[Back](#index)

<a id = 'float'></a>

        float()
The `float()` function converts the argument it is given to a floating point variable (a decimal).  In the example below a string containing the text '6.0' is converted from text (stored in the variable `TXT`) into a decimal (stored in the variable `X`).

In [4]:
TXT = '6.0'
print('TXT is a', type(TXT), 'variable. 2*TXT =', 2*TXT)
X = float(TXT)
print('X is a', type(X), 'variable. 2*X =', 2*X)

TXT is a <class 'str'> variable. 2*TXT = 6.06.0
X is a <class 'float'> variable. 2*X = 12.0


[Back](#index)

<a id = 'int'></a>

        int()
The `int()` function converts its argument, which must be a *number*, to an integer and *always* rounds down.  Below the floating point decimal `FLT`, which is equal to 4.8, is converted to an integer variable, `N`, which is equal to 4, since 4.8 is rounded down.

In [5]:
FLT = 4.8
print('FLT is a', type(FLT), 'variable, and is equal to', FLT)
N = int(FLT)
print('N is a', type(N), 'variable, and is equal to', N)

FLT is a <class 'float'> variable, and is equal to 4.8
N is a <class 'int'> variable, and is equal to 4


What happens if you make `FLT` a string rather than a float by setting `FLT = '4.8'`?

[Back](#index)

<a id = 'str'></a>

        str()
The `str()` function converts its argument to a `string` (a text variable).  In the example below the floating point variable `FLT` is converted to text and stored in the string variable `TXT`.  When we try and multiply `TXT` by 2 instead of getting 9.6 we get 4.84.8.

In [6]:
FLT = 4.8
print('FLT is a', type(FLT), 'variable')
TXT = str(FLT)
print('TXT is a', type(TXT), 'variable')
print('2*TXT =', 2*TXT)

FLT is a <class 'float'> variable
TXT is a <class 'str'> variable
2*TXT = 4.84.8


[Back](#index)

<a id = 'sum'></a>

        sum()
The `sum()` function accepts a list as an argument and the ouput is the sum of the elements of the list.  For example

In [7]:
sum([1, 3, 4, 5.2])

13.2

[Back](#index)

<a id = 'range'></a>
 
        range()
The `range()` function creates a sequence of numbers based on up to three arguments depending on how you call the function.  

In its simplest form, using `range()` with a single integer argument, the function creates a sequence that begins at 0 and has increments of 1 until the value **1 less than the argument** is reached. For example, `range(5)` creates the sequence 0, 1, 2, 3, 4.

The full syntax is

        range(start, stop, step)
        
For example `range(3, 15, 2)` creates the sequence 3, 5, 7, 9, 11, 13.

[Back](#index)

<a id = 'import'></a>

        import
        as
The `import` and `as` commands are used to import special libraries of commands that we may need to use for our specific application.  In the above example the Numerical Python package `numpy` is imported that contains many useful mathematical functions.  To save us writing out `numpy` every time we wish to use a `numpy` function we have imported it `as np` so the we can write `np.pi` for 3.14159265358979... rather than `numpy.pi` etc.  Similarly we have imported the plotting functions in the Mathematical Plotting Library `as plt` so we can write `plt.plot(...` rather than `matplotlib.pyplot.plot(...` every time.

In [8]:
import numpy as np
import matplotlib.pyplot as plt
print('pi =', np.pi)

pi = 3.141592653589793


[Back](#index)

<a id = 'format'></a>
 
        format()
Another way to output values to the screen uses the `format()` function.  The advantage of the `format()` function is that it allows you to control the precision of the output.  For example

In [9]:
vegetable = ['carrot', 'cauliflower', 'bean']
colour = ['orange', 'white', 'green']
mass = [0.235654, 0.42, 0.01563256]
g = 9.81

for i in range(3):
    print('I have a {} that is {} and weighs {:.2f}N'.format(vegetable[i], colour[i], mass[i]*g))

I have a carrot that is orange and weighs 2.31N
I have a cauliflower that is white and weighs 4.12N
I have a bean that is green and weighs 0.15N


You can place curly brackets `{}` in the string where you would like the values of variables (either numerical or text) to appear.  Within the curly brackets you can specify the *format* of the output.  Even though the masses are specified to different levels of accuracy, the ouput in each case is controlled to be two decimal places by putting the formatting statement `:.2f` within the third set of curly brackets.  The order in which you place the variables in the format argument is the order in which they appear in the string.  

How would you change the output to be three decimal places of accuracy for the weight?

What happens if you change the formatting statement to `:.2e`?

[Back](#index)

<a id="operators"></a>
### MATHEMATICAL OPERATORS

        +
        -
        *
        /
        **
Listed above are respectively the mathematical operators for *addition*, *subtraction*, *multiplication*, *division* and raising to a specified *power*.  **Be careful**, even simple calculations can lead to unexpected rounding errors creeping in.

In [10]:
print(2.09 + 1.7)
print(2.09 - 1.7)

3.79
0.3899999999999999


We can use the fact that the positive square root of a non-negative number, $\sqrt{x}$, is equal to the half power, $x^{1/2}$.  For example, to calculate the square root of 9 we can use

In [11]:
9**0.5

3.0

This should only be used for one-off quick calculations, if you are going to calculate square roots repeatedly there are faster methods.

[Back](#index)

<a id="isequal"></a>
### CONDITIONAL STATEMENTS

        ==
The double equals sign `==` is used to determine whether two quantities are equal.  The syntax is `A == B` and the output is `True` if `A` is equal to `B` or `False` if `A` is not equal to `B`.  **Be very careful** - there is a world of difference between the lines of code `A == B` and `A = B`.  See the examples below 

In [12]:
1 + 1 == 2

True

In [13]:
A = 3
B = 4
A == B

False

In [14]:
A = 3
B = 4
A = B

In the second example, where we wrote `A == B`, Python checked to see whether `A` was equal to `B` or not, and decided that since $3 \ne 4$ the answer was `False`.  In the third example, where we wrote `A = B`, Python reassigned the value stored in the variable `A` to the value stored in the variable `B`.  Instead of checking whether `A` was equal to `B` Python changed the value of `A` to 4.  You can check this be writing `print(A)`.

[Back](#index)

<a id="isnotequal"></a>

        !=
To test to see whether two quantites are **not equal** we can use `!=`.  The syntax is the same as for testing for equality.

In [15]:
A = 3
B = 4
A != B

True

[Back](#index)

<a id="inequality"></a>

        >
        <
        >=
        <=
Listed above are respectively the commands to test for *greater than*, *less than*, *greater than or equal to*, and *less than or equal to*.  The syntax is the same as for testing for equality and the output will be either `True` or `False`.

In [16]:
A = 3
B = 4
print(A > B)
print(A < B)
print(A >= B)
print(A <= B)

False
True
False
True


What happens when you change the value of `B` to 3 in the above?

[Back](#index)

<a id="if"></a>
### CONTROL STATEMENTS AND LOOPS

        if
The `if` statement is used if you would like the code to take different actions depending on whether a conditional statement is `True` or `False`.  For example we may wish to divide two numbers `if` the denominator is non-zero.  We could code this as

In [17]:
X = 2.0
Y = 4.0
if Y != 0: # Here we are testing to see whether Y is not equal to zero
    print(X/Y) # This is only executed if Y is not equal to zero
    print(X + Y) # This is only executed if Y is not equal to zero

0.5
6.0


What happens if we change `Y = 4.0` to `Y = 0.0` in the above example?  The syntax for an `if` statement is

        if <conditional statement>:
            <consequent>

The colon after the conditional statement and the indentation in the following lines of code are essential.  All indented lines will be executed `if` the conditional statement is `True`.

[Back](#index)

<a id="else"></a>

        else
We may wish our code to take one of two actions depending on whether a conditional statement is `True` or `False`.  In the above example we printed the value of `X/Y` to the screen [`if`](#if) `Y` was not equal to zero.  We could choose to display a warning message to the user, for example `if` `Y` is equal to zero.  The syntax is

        if <conditional statement>:
            <consequent>
        else:
            <alternative>
            
Hence, we could change our example above to

In [18]:
X = 2.0
Y = 0.0
if Y != 0: # Here we are testing to see whether Y is not equal to zero
    print(X/Y) # This is only executed if Y is not equal to zero
    print(X + Y) # This is only executed if Y is not equal to zero
else: # The following lines are only executed if Y is equal to zero
    print('Attempt to divide by zero')
    print('Not a good idea')

Attempt to divide by zero
Not a good idea


In this case, because `Y` is equal to 0 all the indented lines beneath the `else` statement were executed.

[Back](#index)

<a id="is"></a>

        is
Depending on how you code your conditional statement you may wish to test whether something `is` `True` or `False`.  For example

In [19]:
X = -3
BOOL = (X >= 0)

if BOOL is True: # then we have that X >= 0
    print('The variable X is greater than or equal to zero.')
else: # we have that X < 0
    print('The variable X is negative.')

The variable X is negative.


In the example above we define a variable `X` to be whatever number we like (see what happens when you change it).  We then set the variable `BOOL` to be equal to the output of the statement `X >= 0`.  The output of `X >= 0` is `True` if `X` is greater than or equal to zero, or `False` if `X` is less than zero.  The `if` statement then outputs the appropriate text depending on whether `BOOL` `is` `True` or `False`.

[Back](#index)

<a id="while"></a>

        while
A `while` statement will repeatedly execute the indented lines of code that follow the `while` statement *while* the given conditional statement is `True`.  The syntax is

        while <conditional statement>:
            <exectuable>
            
For example, to countdown to launch we could use

In [20]:
T = 10 # Set the initial countdown length
print('Lift off in:')

while T > 0: # If T is greater than zero keep iterating
    print(T, 'seconds') # Print to the screen how long is left
    T -= 1 # Reduce the number of seconds to lift off by 1
    
print('BLAST OFF!')

Lift off in:
10 seconds
9 seconds
8 seconds
7 seconds
6 seconds
5 seconds
4 seconds
3 seconds
2 seconds
1 seconds
BLAST OFF!


What happens if you change the line `T -= 1` to `T = T - 1` or `T -= 2`?

To calculate a factorial we could use a `while` loop in the following way

In [21]:
N = 5
print(str(N) + '! = ', end = '')
N_factorial = N

while N > 1:
    N_factorial = N_factorial*(N - 1)
    N -= 1
    
print(N_factorial)

5! = 120


A `while` loop will keep executing the indented code until the conditional statement is `False`.  You therefore **need to be very careful** that at some point your conditional statement will be false, otherwise your code will hang.

[Back](#index)

<a id="for"></a>

        for
        in
Similarly to a [`while`](#while) loop we may wish to execute lines of code repeatedly but with a given variable taking a different value from a specified [`range`](#range) or list on each loop.  This is a `for` loop.  We could redo our countdown and factorial loops using `for` instead of [`while`](#while) in the following way

In [22]:
print('Lift off in:')

for T in range(10, 0, -1):
    print(T, 'seconds') # Print to the screen how long is left
    
print('BLAST OFF!')

Lift off in:
10 seconds
9 seconds
8 seconds
7 seconds
6 seconds
5 seconds
4 seconds
3 seconds
2 seconds
1 seconds
BLAST OFF!


In [23]:
N = 5
N_factorial = 1

for I in range(2, N + 1):
    N_factorial = N_factorial*I

print(str(N) + '! =', N_factorial)

5! = 120


In the first example above we allowed the variable `T` to start at 10 and decrease by 1 each time we went through the `for` loop.  In the second example above we allowed the variable `I` to start at 2 and increase by 1 each time until it reached the value `N` (Note: **it does not reach** `N+1`).

We can also use `for` loops as part of a list comprehension.  For example

In [24]:
n = range(10)
n_squared = [i**2 for i in n]
print(n_squared)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In the above example we set `n` to be the sequence of values from 0 to 9 in increments of 1.  Then we created the list `n_squared` whose elements were $i^2$ for every $i$ that Python found in the sequence `n`.

[Back](#index)

<a id=abs></a>
### SPECIAL MATHEMATICAL FUNCTIONS

        numpy.abs()
        numpy.sqrt()
        numpy.exp()
        numpy.log()
        numpy.cos()
        numpy.sin()
        numpy.tan()
        numpy.arccos()
        numpy.arcsin()
        numpy.arctan()
        
Listed above are standard mathematical special functions that you are familiar with from school, absolute value, square root, exponential etc.  The only things to watch are: the natural logarithm is `numpy.log()`, or `np.log()` if you imported `numpy as np`, the natural logarithm *is not* `numpy.ln()`; the inverse trigonometric functions are `numpy.arcsin()` etc., not `numpy.asin()`.

In [25]:
import numpy as np
4.0*np.arctan(np.sin(np.pi/2))

3.141592653589793

The example above calulates
$$4\left\{\tan^{-1}\left[\sin\left(\frac{\pi}{2}\right)\right]\right\} = 4\left\{\tan^{-1}\left[1\right]\right\} = 4\left\{\frac{\pi}{4}\right\} = \pi.$$
[Back](#index)

<a id="array"></a>
### SPECIAL MATHEMATICAL FUNCTIONS: MATRICES

        numpy.array()
The `numpy.array()` function accepts a list of matrix rows as its argument, where each matrix row is itself a list containing the column entries.  A $2\times3$ array would therefore require an input list containing two lists of three elements, such as

In [26]:
import numpy as np
P = np.array([[1, 2, 3], [4, 5, 6]])
print(P)

[[1 2 3]
 [4 5 6]]


Whereas a $3\times2$ matrix would require a list containing three lists each of two elements.  Look at the difference between the two examples.

In [27]:
import numpy as np
Q = np.array([[1, 2], [3, 4], [5, 6]])
print(Q)

[[1 2]
 [3 4]
 [5 6]]


[Back](#index)

<a id="zeros"></a>

        numpy.zeros()
The `numpy.zeros()` function creates a matrix of zeros with the shape specified by its argument which must be entered as two integers separated by a comma in round brackets where the number of rows created is the first integer and the number of columns created is the second integer (this is an example of a tuple).  To create the $3\times5$ zero matrix therefore we would use

In [28]:
import numpy as np
A = np.zeros((3, 5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[Back](#index)

<a id="matmul"></a>

        numpy.matmul()
The `numpy.matmul()` function uses matrix multiplication to multiply together its two arguments.  The arguments therefore must satisfy the shape requirements to allow for them to be multiplied together.  For example we can multiply the $2\times3$ matrix **P** with the $3\times2$ matrix **Q** defined above to get the $2\times2$ matrix **P**$\times$**Q** as follows

In [29]:
import numpy as np
P = np.array([[1, 2, 3], [4, 5, 6]])
Q = np.array([[1, 2], [3, 4], [5, 6]])
np.matmul(P, Q)

array([[22, 28],
       [49, 64]])

What happens when we calculate **Q**$\times$**P**?  What happens when we try to calculate **P**$^2$?

[Back](#index)